spring.application.name=vehiculo


spring.datasource.url=jdbc:mysql://localhost:3310/vehiculo_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# desactivar creacion automatica de tablas con hibernate
spring.jpa.hibernate.ddl-auto=none

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# credenciales para spring security / postman
# spring.security.user.name=admin
# spring.security.user.password=1234